apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config-python-predictor
  namespace: {{.Values.deployment.application_name}}
data:
  agent.cfg: |-
    [agent]
    app = healthcare
    tier = bookingService
    node = bookingService
    [controller]
    host = XYZ.saas.appdynamics.com
    port = 80
    ssl = off
    account = ACCOUNT_NAME
    accesskey = ACCESS_KEY
